### ISSUE TITLE
首頁下方 "主辦機關" 加上屏科大野生動物保育所 logo

### ISSUE THREAD

**Issue by moogoo78** [TaiBIF/camera-trap-api-2020#6]
![野保所_所徽_無字](https://user-images.githubusercontent.com/428769/96818433-13631100-1454-11eb-8b0d-bcf8a663bcfa.jpg)

**Comment by v02202** [comment]
已加入

**Comment by moogoo78** [comment]
有 commit 嗎 ?

**Comment by moogoo78** [comment]
fixed https://github.com/TaiBIF/camera-trap-vueapp-2020/commit/73aae107057aa1efd3c5e465a4b11f2b9597a8e7
